name: PHP CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  php:
    name: PHP project (PHP ${{ matrix.php-versions }})

    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    strategy:
      fail-fast: true
      matrix:
        php-versions: ['7.4', '8.0']

    steps:
      # Setup Github actions
      # https://github.com/actions/checkout (official)
      - name: Checkout
        uses: actions/checkout@v2

      # Setup PHP
      # https://github.com/shivammathur/setup-php (community)
      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer

      - name: Install Project
        run: make install

      - name: Check for code quality errors
        run: make lint

      - name: Run Unit tests
        run: make tests
